// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-u-OEdZZP75gpKmMsKgJGNBqRzrJfF-Q',
    appId: '1:222920556714:web:bcbbe5ea29748f7d2190d3',
    messagingSenderId: '222920556714',
    projectId: 'stal-9bec9',
    authDomain: 'stal-9bec9.firebaseapp.com',
    storageBucket: 'stal-9bec9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ2FLvbwMnvfny2n2-rLzcyytkLbSG6XE',
    appId: '1:222920556714:android:ed3001cc1e7f391e2190d3',
    messagingSenderId: '222920556714',
    projectId: 'stal-9bec9',
    storageBucket: 'stal-9bec9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8kZHi-XT80j3fZybV4cdLPECupxszAC4',
    appId: '1:222920556714:ios:e35e524c3f03855f2190d3',
    messagingSenderId: '222920556714',
    projectId: 'stal-9bec9',
    storageBucket: 'stal-9bec9.appspot.com',
    iosBundleId: 'com.example.stal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8kZHi-XT80j3fZybV4cdLPECupxszAC4',
    appId: '1:222920556714:ios:e35e524c3f03855f2190d3',
    messagingSenderId: '222920556714',
    projectId: 'stal-9bec9',
    storageBucket: 'stal-9bec9.appspot.com',
    iosBundleId: 'com.example.stal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-u-OEdZZP75gpKmMsKgJGNBqRzrJfF-Q',
    appId: '1:222920556714:web:50f15487b864b1e52190d3',
    messagingSenderId: '222920556714',
    projectId: 'stal-9bec9',
    authDomain: 'stal-9bec9.firebaseapp.com',
    storageBucket: 'stal-9bec9.appspot.com',
  );
}
